#pragma config(Sensor, in4,    potCon1,        sensorPotentiometer)
#pragma config(Sensor, in5,    potCon2,        sensorPotentiometer)
#pragma config(Sensor, in6,    potCon3,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  conLED1,        sensorDigitalOut)
#pragma config(Sensor, dgtl2,  conLED2,        sensorDigitalOut)
#pragma config(Sensor, dgtl3,  conLED3,        sensorDigitalOut)
#pragma config(Sensor, dgtl4,  alexBUMP1,      sensorTouch)
#pragma config(Sensor, dgtl5,  alexBUMP2,      sensorTouch)
#pragma config(Sensor, dgtl6,  alexBUMP3,      sensorTouch)
#pragma config(Sensor, dgtl7,  alexLED1,       sensorDigitalOut)
#pragma config(Sensor, dgtl8,  alexLED2,       sensorDigitalOut)
#pragma config(Sensor, dgtl9,  alexLED3,       sensorDigitalOut)
#pragma config(Sensor, dgtl10, alexBUMP4,      sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		if ((alexBUMP1) == 1) ;{
			resetTimer(T1);
			resetTimer(T2);
			resetTimer(T3);
			if ((potCon1) == 1600) {
				repeatUntil (getTimer(T1, seconds) == 10) {
					if ((potCon2) == 1600);
 {
						((conLED2) == 0);
					}
					if ((potCon3) == 1) {
						((conLED3) == 0);
					}
				}
				((conLED1== 100);
				waitUntil (getTimer(T1, seconds) == 10);
				((conLED1) == 0);
			} else {
				((conLED1) == 0);
			}
			if ((potCon2) == 1) {
				repeatUntil (getTimer(T2, seconds) == 10) {
					if ((potCon1) == 1) {
						((conLED1 == 0);
					}
					if ((potCon3) == 1) {
						((conLED3 == 0);
					}
				}
				((conLED2 == 100);
				waitUntil (getTimer(T2, seconds) == 10);
				((conLED2) == 0);
			} else {
				((conLED2) == 0);
			}
			if ((potCon3) == 1) {
				repeatUntil (getTimer(T3, seconds) == 10) {
					if ((potCon1) == 1) {
						((conLED1 == 0);
					}
					if ((potCon2) == 1) {
						((conLED2 == 0);
					}
				}
				((conLED3) == 100);
				waitUntil (getTimer(T3, seconds) == 10);
				((conLED3) == 0);
			} else {
				((conLED3) == 0);
			}
		}
	}
