#pragma config(Sensor, in6,    potCon1,        sensorPotentiometer)
#pragma config(Sensor, in7,    potCon2,        sensorPotentiometer)
#pragma config(Sensor, in8,    potCon3,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  conLED1,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  conLED2,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  conLED3,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  alexBUMP1,      sensorTouch)
#pragma config(Sensor, dgtl5,  alexBUMP2,      sensorTouch)
#pragma config(Sensor, dgtl6,  alexBUMP3,      sensorTouch)
#pragma config(Sensor, dgtl7,  alexBUMP4,      sensorTouch)
#pragma config(Sensor, dgtl8,  alexLED1,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  alexLED2,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, alexLED3,       sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

 task contestant_1(){ //code for the contestant buzzer
  if(SensorValue(potCon1) < 2000){ //starts if potentiometer is turned
   turnLEDOn(conLED1); //turns on contestant light
   wait(10); //keep light on for 10 seconds
   turnLEDOff(conLED1);} //turn light off
  else{
  	turnLEDOff(conLED1);}} //keep light off if potentiometer isnt turned

 task contestant_2(){
   if(SensorValue(potCon2) < 2000){
    turnLEDOn(conLED2);
    wait(10);
    turnLEDOff(conLED2);}
   else{
     turnLEDOff(conLED2);}}

 task contestant_3(){
  if(SensorValue(potCon3) < 2000){
    turnLEDOn(conLED3);
    wait(10);
    turnLEDOff(conLED3);}
  else{
  	turnLEDOff(conLED3);}}


task main(){
	while(1>0){
		if(SensorValue(alexBUMP1) == 1){ //alex's first button starts program
	   while(true){
	    startTask(contestant_1); //runs if contestant 1 buzzes in
 	    startTask(contestant_2); //runs if contestant 2 buzzes in
	    startTask(contestant_3); //runs if contestant 3 buzzes in
	    turnLEDOn(alexLED1); //turns on alex's light
     if(SensorValue(alexBUMP4) == 1){ //shuts down program if alex's fourth button is pressed
       turnLEDOff(alexLED1); //turns off alex's light
	     stopAllTasks();}
     if(SensorValue(alexBUMP2) == 1){ //if alex's second button is pressed the correct light turns on
       turnLEDOn(alexLED2);} //correct light is turned on
     else{
       turnLEDOff(alexLED2);}
     if(SensorValue(alexBUMP3) == 1){ //if alex's third button is pressed the incorrect light turns on
       turnLEDOn(alexLED3);} //incorrect light is turned on
     else{
       turnLEDOff(alexLED3);}}}}}
