#pragma config(Sensor, in4,    potCon1,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  conLED1,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  alexBUMP1,      sensorTouch)
#pragma config(Sensor, dgtl7,  alexLED1,       sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

  do
 {
   turnLEDOn(conLED1);
   waitInMilliseconds(5000);
 }
   while(SensorValue(potCon1) < 2000);

}

 do
 {
   turnLEDOn(conLED1);
   turnLEDOff(conLED2);
   turnLEDOff(conLED3);
 }
  while(SensorValue(potCon1) < 2000);

